# Dependencies
highlighter:      rouge
markdown:         kramdown
kramdown:
   input:         GFM  # Enable GitHub Flavored Markdown (fenced code blocks)

# Permalinks
permalink:        pretty

# Setup
title:            "( . .)Ï†__"
tagline:          "Coding Notes"
description:      "Reference for Git, R, HTML, CSS and JS"
url:              http://yahwes.github.io/code-reference
baseurl:          /
paginate:         5

author:
  name:           'Janet Wesner'
  url:            https://twitter.com/lolatu2
  email:          janet.wesner@outlook.com
  github:         https://github.com/yahwes

# Assets
sass:
  style:            :compressed
 
# Custom vars
version:          0.1
github:
  repo:           https://github.com/yahwes/code-reference

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist